trigger:
  branches:
    include:
    - master
  paths:
    include:
    - site.hs

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack

- task: Cache@2
  inputs:
    key: 'stack | root'
    path: .stack/
    cacheHitVar: 'STACK_SNAPSHOT_RESTORED'

- task: Cache@2
  inputs:
    key: 'stack | stack.yaml.lock'
    path: .stack-work/
    cacheHitVar: 'STACK_DEPS_RESTORED'

- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --stack-root $(System.DefaultWorkingDirectory)/.stack setup
  displayName: Build Snapshot
  condition: ne(variables.STACK_SNAPSHOT_RESTORED, 'true')

- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --stack-root  $(System.DefaultWorkingDirectory)/.stack build
  displayName: Build Dependencies
  condition: ne(variables.STACK_DEPS_RESTORED, 'true')

- script: |
    export PATH=$HOME/.local/bin/$PATH
    stack --no-terminal --stack-root $(System.DefaultWorkingDirectory)/.stack install --local-bin-path $(Build.ArtifactStagingDirectory)/bin
  displayName: Build Site Executable

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/bin'
    artifact: 'site'
    publishLocation: 'pipeline'
