trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  steps:
  - script: |
      mkdir -p ~/.local/bin $(Build.BinariesDirectory)
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    displayName: Install Stack
  - task: Cache@2
    inputs:
      key: 'stack | root'
      path: .stack/
      cacheHitVar: 'STACK_SNAPSHOT_RESTORED'
  - task: Cache@2
    inputs:
      key: 'stack | stack.yaml.lock'
      path: .stack-work/
      cacheHitVar: 'STACK_DEPS_RESTORED'
  - script: |
      export PATH=$HOME/.local/bin:$PATH
      stack --no-terminal --stack-root $(System.DefaultWorkingDirectory)/.stack setup
    displayName: Build Snapshot
    condition: ne(variables.STACK_SNAPSHOT_RESTORED, 'true')
  - script: |
      export PATH=$HOME/.local/bin:$PATH
      stack --no-terminal --stack-root  $(System.DefaultWorkingDirectory)/.stack build
    displayName: Build Dependencies
    condition: ne(variables.STACK_DEPS_RESTORED, 'true')
  - script: |
      export PATH=$HOME/.local/bin:$PATH
      stack --no-terminal --stack-root $(System.DefaultWorkingDirectory)/.stack install --local-bin-path $(Build.BinariesDirectory)
    displayName: Build Site Executable
    condition: ne(variables.SITE_BIN_RESTORED, 'true')
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.BinariesDirectory)
      artifactName: site

- job: deploy_draft
  dependsOn: build
  condition: and(succeeded(), ne(variables['build.sourceBranchName'], 'master'))
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download site binary
    inputs:
      artifactName: site
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: |
      export PATH=$(System.DefaultWorkingDirectory)/site:$PATH
      chmod +x $(System.DefaultWorkingDirectory)/site/site
      export HAKYLL_ENV=development
      site build
    displayName: Build Static Site
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '_site'
      artifact: 'draft'
      publishLocation: 'pipeline'

- job: deploy_published
  dependsOn: build
  condition: and(succeeded(), eq(variables['build.sourceBranchName'], 'master'))
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download site binary
    inputs:
      artifactName: site
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: |
      export PATH=$(System.DefaultWorkingDirectory)/site:$PATH
      chmod +x $(System.DefaultWorkingDirectory)/site/site
      site build
    displayName: Build Static Site

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: 'nexus.mrlee.dev,51.195.169.24 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOpVslp9zKHmQW02IqhM8rNWrFsohWUxLaLpU/aFNhr0B8L4ue0SAvRoKX6sPNbTiFnm7IsqPqR5Hu+Sjd4INqv1DkoMNH7e7idxeDqRInlXEX78XtJOUkXLLmlTgn0hANfXevw6YyMTWp2PWa/gh3Z+sLMMuJA2WorMnQ37uFdR3SbIxxssbio4FpPhbB1Kqf0BgXS+PbBNa7Lw4Fa0QdpGllg+1weEaA+JYA0ySO5lyDiAOXl5F8i82Un0QACywzjV6RlF2YLSDXtio9ma+Qrou85xmP3bG+HsiMu5LyI662NA1sy5/Bu4dVyyyoKbFFkczYxU2w3VNYMnv6+iH/'
      sshKeySecureFile: 'nexus_deploy'
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'Nexus'
      sourceFolder: '_site/'
      contents: '**'
      targetFolder: '/var/www/www.mrlee.dev/'
      cleanTargetFolder: true
      readyTimeout: '20000'