image: debian/bullseye
sources:
  - https://git.sr.ht/~mrlee/www.kamelasa.dev
packages:
  - emacs
secrets:
  - f74304b4-9735-47a4-9d23-6d9fd7c47f1a
tasks:
  - check-branch: |
      cd www.kamelasa.dev
      if [ "$(git rev-parse main)" != "$(git rev-parse HEAD)" ]; then
        complete-build;
      fi
  - publish: |
      cd www.kamelasa.dev
      emacs --batch --load publish.el --funcall org-publish-all
      scp -o StrictHostKeyChecking=no -r ../www/* deploy@kamelasa.mrlee.dev:/var/www/kamelasa.dev
