baseURL = 'https://www.leemeichin.com'
copyright = 'Lee Meichin (2021-2023)'
enableRobotsTXT = true

[author]
  name = 'Lee Meichin'

[params]
  title = 'Lee Meichin'
  description = 'Special topics in calamity software dev'
  dateFormat = '2006-01-02'
  generateSocialCard = false

[markup]
  [markup.highlight]
    lineNos = false
    lineNosInTable = false
    noClasses = false
  [markup.goldmark.renderer]
    unsafe= true

[module]
[[module.imports]]
  path = 'github.com/clente/hugo-bearcub'
