baseURL = 'https://www.leemeichin.com'
enableRobotsTXT = true
title = 'Lee Meichin'

[author]
  name = 'Lee Meichin'

[params]
  author = 'Lee Meichin'
  footer = '&copy; 2020-2023 Lee Meichin 🥰'
  enable_toc = true
  enable_collapsible_changelogs = true
  enable_collapsible_toc = true
  enable_site_search = true
  enable_open_graph = true
  enable_twitter_cards = false

  [params.list_layout]
    enable_group_by_year = true
    enable_show_date = true
    enable_pagination = true

  [params.syntax_highlight]
    lib = 'prism.js'
    [params.syntax_highlight.prism]
      enable_code_copy = true
      enable_line_no = false

[[menu.navbar]]
identifier = 'sqlcss'
name = 'sqlcss'
title = 'sqlcss'
url = 'https://sqlcss.leemeichin.com'

[markup]
  [markup.highlight]
    lineNos = false
  [markup.goldmark.renderer]
    unsafe= true

[outputs]
home = ['HTML', 'RSS', 'JSON']

[module]
[[module.imports]]
  path = 'github.com/janraasch/hugo-bearblog'
