baseURL = 'https://www.leemeichin.com'
languageCode = 'en-gb'


[params]
  themeColor = 'blue'
  showMenuItems = 0
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  enableGitInfo = true
  showLastUpdated = true
  readingTime = true

[languages]
  [languages.en]
    title = 'Lee Meichin'
    description = 'Special Topics in Calamity Software Dev'

    [languages.en.params.logo]
      logoText = 'kamelåså'
      logoHomeLink = '/'

[markup.goldmark.renderer]
unsafe= true

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'
