#+TITLE: Emotional Debt
#+DATE: 2022-07-13
#+CATEGORY: personal

Another day, another post about burnout. But really, I'm thinking more about that point that precedes it, the stall that--left unchecked--turns into a nosedive. The good thing is you do have an opportunity to pull back up, you always do, but it gets harder the longer you wait.

The last few years have been different and difficult for everyone, regardless of physical or mental health. I'm not going to explore any of that because I don't have anything to contribute that you won't find in the total saturation of commentary on the topics; this is just to acknowledge that I feel it and it hurts that in an age of unprecedented progression and prosperity, for 1% of of humanity to take a step forward, 99% seems to have to take two steps back.

It's ironic that I've called this 'emotional debt' then because it sounds like a very un-feeling way to talk about feelings: emotion, empathy, compassion...all the good stuff that makes you want to love (or at least tolerate) and not hate. I'm using this to describe the feeling of running low on battery, just before it depletes and your brain powers down.

At some point you've given more than what you've got and you can keep giving, and giving... eventually there's less than nothing to give so it starts becoming a burden, it messes with your mood. Where are /you/ in all of this, as in, your actual /self/? There's not much left for you after you're so completely spent.

The more resilient you are, the more time you can buy for yourself, but it's not forever is it? The law of physics states that energy cannot be created or destroyed, it can only be converted, so in order for you to be able to decently recover it follows that you have to stop doing one thing and replace it with something else, even if only temporarily (as with a two-week holiday, or even more drastically, a career change or moving country).

Mixed metaphors abound in this post! But I think that's what mental health, and mental and emotional energy is...isn't one single way to describe it that makes total sense.

How do you repay emotional debt? For me, it means I have to be better at carving out time for myself so I can better meet my own needs, but that's hard when I'm habitually attuned to putting other people before me. Childhood trauma for the therapist, really.

I try to solve it by distraction, which only works for so long before it wears off. I'm a bit of a workaholic, for example, and it's more psychologically safe for me to replace a life-problem with a work-problem /even if/ my work actually suffers from it over time and simple problems feel ten times harder than they should be. It's like knocking back cans of Red Bull to keep me awake, when nothing would help me better than just going to fucking sleep.

Behind the scenes, there is always that lingering doubt about there being more to this than meets the eye. The Sword of Damocles dangles above and 'depression' is engraved into the hilt. Is it? Is it not?

That's kind of where I've been for the past, say, three or four months. Not completely burned out, but well on the way to it.

No advice this time, just using my blog for me.
