#+TITLE: Integrity
#+DATE: <2024-11-13>
#+CATEGORY: personal

I don't intend to do a political deep-dive here, but it's fairly obvious that last week's election in the US has weighed on my mind somewhat. Let's get it out of the way: I'm not conservative, and the recent conduct of conservative and right-wing politicians both here in the UK and abroad goes against everything I stand for. That doesn't automatically mean I have nothing but love for people on the left or 'on my side'--presuming I even have a side that I support unwaveringly--I just know what I stand for and what I don't.

If hearing that is enough for you to close the page and move on, then so be it. I'm not really going to talk about that any more.

So... integrity. Integrity, in one sense, is how well you hold up to external pressure. Outside forces will push you and pull you in different directions, will ask you to stretch beyond your limits, will try to break down the very foundations you stand upon. People, processes, systems...it's all the same, they all want you to fold.

To maintain integrity is to stay consistent in what you believe, in what drives you. It offers a sense of continuity in an ever changing world where those beliefs and motivations are frequently challenged. On the surface, this paints a very uncompromising picture of a person, but in the details you find flexibility and pragmatism that allows for growth and adaptation without sacrificing your core principles.

Easier said than done, right? Especially when emotions are running high, you're upset, and in a desperate moment of catharsis you want to lash out and get that frustration out of your system.

I feel like the social segment of the internet is an echo chamber, but not in the way that people think it is. It's a two-dimensional space keyed by engagement and reach, and the things that create engagement and reach farthest change with the zeitgeist. Or more likely they /create/ the zeitgeist, as the social component of the media creates an amplifying feedback loop.

Social media, in that sense, is a flawed simulation of the real world that runs in parallel but is often mistaken for the real thing. From a distance you could be mistaken, but the illusion is lost as you move closer to the mirror and see how distorted it really is. The truer you stay to yourself, though, the more those images remain comparable, the more you know you're not letting your alternate personality loose under the guise of anonymity.

Every time you participate and post a message of hate or anger against other people you previously supported, you have to wonder... are you staying true to yourself? Or was that conditional on things going your way?

I have no love for people I feel voted against the interest of the average person: themselves, myself, others...but am I willing to throw away everything I care about to try and get my own back?

When I said I wouldn't bring up politics again, I lied. What triggered this post was seeing highly upvoted content on Reddit calling for Trump-voting immigrants to be deported, ostensibly as revenge for betrayal. You don't really know these days if that sentiment is legitimate or if it's just posted to inflame tensions and create more engagement, but let's take it at face value and deconstruct it.

Firstly, from a progressive standpoint, we can make the assumption that such a person considers themselves an LGBTQ+ ally and believe in equality such that the systemic bias against minorities or marginalised people needs to be addressed, amongst other things. Secondly, the concept of a Republican administration, let alone a Trump one, is deemed to be an existential threat to those people. Trump and his entourage have been called fascists and Nazis.

Why then, in response to a poor election result, would such a person call for the deportation of marginalised people based purely on their political beliefs? Is that person willing to become everything they are against just to deliver a taste of medicine to minorities who didn't stay in line with the progressive agenda?

You know? Just because a nazi got voted in doesn't mean you hit up the registration centre yourself.

Bringing it back to integrity, this is what I mean. What hope do you have of bouncing back, moving forward, if you crumble at the first sign of trouble?

At the very least you can still be at peace with yourself.
