#+TITLE: More thinking on burnout
#+DATE: <2023-08-13>
#+CATEGORY: personal

Recently I took a month off work in between jobs to give myself a chance to reset. To be honest, the month felt more like a long weekend and it wasn't enough: most of the time was spent recharging and it didn't leave much behind for pursuing more fun activities. What I *did* achieve was still more than I'd managed in the six months prior though, so it was still an improvement.

This got me thinking a bit, so I'm going to lay down some assumptions that have no academic basis but still--I think--speak to something people can relate to.

- Firstly, burnout isn't unique or rare and nor is it always referred to as burnout (see: stress, anxiety, exhaustion)
- Secondly, some people experience the feeling of being burned out more acutely than others (see: resilience)
- Thirdly, due to its link to stress and exhaustion, the effect of burnout is as physical as it is mental
- Finally, you could experience this for quite some time before becoming aware of it (it can slowly accumulate for months or years)

So, how do you deal with it when you find out? The answer I commonly hear or read is to take a long break from work, we're talking maybe six months or a year, to focus on recovery or doing something else.

I have a bone to pick with this answer primarily because it's steeped in economic privilege. *Anybody* would jump at the chance to take a huge break if they could afford it, but life has a way of getting in the way and not everybody manages to acquire the wealth required to pull this off.

I was fortunate to manage even a month of runway, and this is a total non-starter for anyone living payslip to payslip.

So...if *not working* is off the table, what other options are there? I don't have any concrete answers, but here are a few fairly simple things I'm trying out (possibly trying out again, but differently):

## Using physical activity to recharge your battery

This is a pretty obvious thing to start with and I think most people would suggest that the best thing to do is to get active. The problem is that if you're super mentally exhausted you probably don't feel like being active, so you've got to start with something small enough to jump-start your battery and then use the (hopeful) good feeling from that to keep you going. It's like how riding a bike can generate electricity, only you're doing it for yourself.

For me, this is going back to the gym but trying a different routine than the previous one that I didn't like, but physical activity doesn't exclusively have to be gym based. So, when I work at the office I often replace the tube journey with a 30 minute walk.

I won't do both the gym and the walk on the same day because that's overdoing it; it simply means I've got other options to keep up with the habit that require a bit less effort and planning than a gym workout.

## Reading books to change your mindset

I think that, when you're low on mental resources, it can feel like too much effort to do anything but mindlessly scroll through content on the internet and bathe in the quagmire of current affairs, politics, news, outrage, and other people being more superior to you. It passes the time but there isn't really anything to show for it, and especially in the case of Facebook or Instagram it can really amp up that feeling of missing out. It's not good for the soul when the soul needs nourishment more than ever.

For me this simply means that I'll pick up a book instead of pulling the phone out of my pocket, unless I'm actually talking to a friend. I tend to enjoy non-fiction books that help me get to grips with a problem I'm facing, or help me become better at what I do, and I try to pick the kind of book that makes me feel empowered or confident by reading it.

This sounds counter-productive when talking about burnout, but the point is that I will find something fairly light that puts me in a good space while reading it, and leaves me with a more active and empowered mindset. What I'm attempting with this approach is to switch from focussing on my problems to reminding myself that there are solutions, because people have written books about similar problems and described their own solutions. Better to avoid intense emotional deep-dives at this stage, of course.

Commutes are perfect for this, when you want to occupy yourself with *something* while travelling from A to B. So that's what I'm doing.

## Enjoying wellness treats to improve self-esteem

My self-esteem plummets when I'm burned out; I just struggle to feel good in myself and that branches out into various forms of self-criticism. This is a great time to pamper yourself a bit because the simple act of doing so acknowledges that your self-esteem is still above zero. The end result is another boost to self-esteem and your mood.

For me, I have a few go-to options. One is a spa and massage combo that is too expensive to use frequently but raises my peace of mind to the stratosphere (in case of emergency, break glass). Another is getting my hair cut with all the works, usually opting for something that isn't my normal style. In both cases I'm enjoying a treat and turning off my brain for a bit.

But it doesn't have to be so fancy all the time; it's really up to you what you consider a treat. I like going out to the park or sitting outside at a cafe and watching people go by too.

I would aim to have at least one such wellness occasion a week, no matter how simple it is.

## Finding creative outlets to allow for expression

One of the worst aspects of burnout, I think, is how hard it can be to talk to people about it. And oftentimes it's not enough to just talk or it's too intense for anyone but a professional to handle, which is why we have counsellors and therapists.

Talking is one such outlet, but maybe there are other ways to transform this energy (or lack thereof) into something else, or something different to what you do on the daily.

For me, I enjoy sinking into writing which relaxes me while also making me feel like I've achieved something. It's this blog, but also journals and drafts for stories and ideas on how to make a game, and so on.

The point of this really is to just find a way of taking what is within and putting it out there in some form, in a manner of unburdening yourself. Understandably though, I think this particular activity is easier said than done.

## Going easy on yourself to break a downward spiral

Ironic I say this because I am my own worst critic and can be absolutely brutal about myself sometimes. Meanwhile I will give anyone dealing with the same thing the most compassion, understanding and latitude as I can.

I feel like my guard is dropped and I'm fully vulnerable when I'm burned out, so I start finding ways to defend myself from a number of imaginary threats.

This is the epitome of overcommitting and underdelivering, and repeating the cycle each time while playing catchup to previous unmet expectations.

I think you just have to lay off on yourself a bit and understand that nobody else is beating you up except you. By you I also mean me, of course, but I've seen this in other people as much as I see it in myself.

## Recording your progress as a method of recognition

Ultimately, you're going to find your own way to deal with burnout and mitigate the effects of it, maybe even overcome it given enough time and patience.

My favourite way of tracking this is through little gratitude journals and jotting down the things I managed to do on my calendar, because a calendar after all is just a reminder of events in a convenient chronological layout. Right now it has 'wrote a blog post' and 'went to the gym' on 13 Aug 2023.


The entire reason for this is to remember what you *can* do, *can* manage, and use it as a confidence boost to remind you that, no matter how hard a time you're having, you've got this.

---

My goal with this is that I'll take these thoughts and apply them in practice for 60 days, and then see how it turned out at the end and write about it.