#+TITLE: Violence
#+DATE: <2022-03-30>
#+CATEGORY: personal

This is a bit of an unusual twist for me, in terms of what I generally write about, because I don't really care about the world of celebrity that much. But something has been on my mind over the past few days since we saw a famous actor, Will Smith, hitting a famous comedian, Chris Rock, on stage, and then hurling some threats from back in his seat.

Way back in 2011, I was on the receiving end of domestic abuse from the man who, at the time, was my sister's boyfriend. I'm not going to retell this story in detail because that's really between me and my therapist these days, suffice to say that family drama had broken out at an alcohol-fuelled Christmas party, I was threatened when attempting to de-escalate, and the next day I found myself pinned against the wall with this man's hands gripped tightly around my throat, with a completely expressionless look on his face. I don't know how long he had me in that position, you don't really keep track of time when being choked out, but he was back playing happy family with everyone else while I was on the phone to the police, struggling to articulate what had just happened.

Eventually I was pressured by family to drop the case against this man because he was already going to prison anyway, so why not have some sympathy for him? After over a decade I still cannot find words that describe the intensity of this betrayal; I was gaslit by my mum and my dad threatened me with 'consequences' that I don't care to remember.

When it comes to domestic abuse there are a litany of go-to phrases that enablers will use to give the aggressor a pass: he didn't mean it, he's going through a lot right now, stop rocking the boat, be the bigger man, you were basically asking for it, you should have manned up and fought back, they're going to get married so you're going to have to live with him, etc. etc.

I understand that deep down, these enablers are just trying to cover up their own discomfort and it's easier to get a compliant victim to shut up than it is to /actually be/ the bigger person and hold the abuser to account. They traded my trust in them, and my relationship with them, for some momentary comfort.

The problem with male-male violence of this kind is that it's not taken very seriously or it's dismissed as some squabble, two men going toe to toe.

Can you see where I'm going with this?

There's a decent amount of hero worship going around for Chris Rock because he didn't retaliate and didn't press charges. He might be a hero for other reasons, but not for being silenced after being attacked on live TV and witnessing a several-minute long standing ovation for the same man mere moments later.

It's the same bullshit playbook as always, where the abuser is twisted into being the real victim: Chris was asking for it because he provoked Will with a joke, Will's going through a lot right now, etc. etc.

It doesn't really matter if he is going through a lot, so is everybody-fucking-else. If you cope by making someone else responsible for your inner-turmoil by taking your anger out on them then you are not coping, and are not building resilience, and are not dealing with your shit in a healthy way.

You can also be compassionate with someone while also holding them accountable for their poor behaviour, it's not a zero-sum game.

I'm imagining a response to this which is something like, "Lee, why are you taking this so seriously?" or "Dude, you're just projecting your own trauma onto another unrelated situation." To which I say, maybe I am, but I'm not wrong.

I would invite you to place yourself in the shoes of someone like Chris Rock, or anyone on the receiving end of abuse. If someone you love has suffered from this, why not take a look from their perspective instead and bring it closer to home. Then, imagine yourself being physically attacked and verbally abused by a clearly unhinged person who went from laughing to /enraged/ within the space of a few seconds. Now, imagine wanting to react to this or respond in some way but feeling unable to. "You can't go against Will Smith, he's so wholesome!"

Finally, wait a day and check the internet and see your attack turned into a meme, everybody laughing.

Personally, the line was already crossed a long time ago, but the overall reaction retreats over the line and crosses it again.

I think it's fucking disgusting that people are joking about it, presumably thinking that Chris Rock's non-reaction means it's okay to make more jokes out of it? Or because it's male-male violence it's all good, they'll just man it out?

It's not a laughing matter, it's making an absolute mockery of the victim and glorifies the aggressor; it's implicit validation. Presumably this is the same discomfort I described before, where a compliant victim is easier to deal with than a wildcard aggressor.

I guess that's all I have to say.
